{{- if .Values.transmissionContext.ingressExternalPrivate.enabled -}}
{{- $fullName := include "transmissionContext.fullname" . -}}
{{- $name := include "transmissionContext.name" . -}}
{{- $ingressPath := .Values.transmissionContext.ingressExternalPrivate.path -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $name }}-external-private
  labels:
    app: {{ template "transmissionContext.name" . }}
    chart: {{ template "transmissionContext.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.transmissionContext.ingressExternalPrivate.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if and .Values.transmissionContext.ingressExternalPrivate.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.transmissionContext.ingressExternalPrivate.ingressClassName }}
  {{- end }}
{{- if .Values.transmissionContext.ingressExternalPrivate.tls }}
  tls:
  {{- range .Values.transmissionContext.ingressExternalPrivate.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.transmissionContext.ingressExternalPrivate.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $name }}
                port:
                  number: 80
              {{- else }}
              serviceName: {{ $name }}
              servicePort: http
              {{- end }}
  {{- end }}
{{- end }}
