apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
  # namespace: redis-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
