---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-smb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "smb"
  resources:
    requests:
      storage: 3580Gi
  volumeName: "csi-smb-pv-smb-transmission-seed"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-torrents
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
