---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 270Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-torrents
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
