---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-transmission
  labels:
    app: {{ template "transmissionContext.name" . }}
    chart: {{ template "transmissionContext.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  k8s-transmission.ovpn: {{ .Values.transmissionContext.ovpn_client | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-rpc
  labels:
    app: {{ template "transmissionContext.name" . }}
    chart: {{ template "transmissionContext.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  user: {{ .Values.transmissionContext.credentials.username | b64enc }}
  password: {{ .Values.transmissionContext.credentials.password | b64enc }}
type: Opaque
