apiVersion: v2
name: transmission-openvpn
description: Transmission torrent client with WebUI while connecting to OpenVPN.
icon: https://bananaspliff.github.io/geek-charts/transmission-openvpn/logo/transmission.png
home: https://bananaspliff.github.io/geek-charts/
sources:
  - https://bananaspliff.github.io/geek-charts/
dependencies:
  - name: transmission-openvpn
    repository: https://bananaspliff.github.io/geek-charts/
    version: 0.1.0

type: application

# renovate: datasource=helm depName=transmission-openvpn repository=https://bananaspliff.github.io/geek-charts/
version: "0.1.0"

# Note: Using haugene/transmission-openvpn Docker image
appVersion: "1.0"
